### ISSUE TITLE
Not running the analysis_plot_h.py

### ISSUE THREAD

**Issue by satoshifuku** [satoshifuku/Body_perception#15]
@hani1986ye 

I cannot get cleaned data in /Data_cleaned/.
you explained the following.
> The cleaned data are stored in another directory "./Analysis/Data_cleaned/[n]/Exp_[date].csv", 

I want you need your advice to run your script.
Now I have the following is error message.

```
./Data\01
"./Data\01\collected_h.csv" is used to plot the boundaries.
No such file
Traceback (most recent call last):
  File ".\analysis_plot_h.py", line 124, in <module>
    main()
  File ".\analysis_plot_h.py", line 104, in main
    plot_boundaries(data_dir, filename, i)
  File ".\analysis_plot_h.py", line 67, in plot_boundaries
    ax1.plot(data[0,:], data[1,:])
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by hani1986ye** [comment]
@satoshifuku 

Sorry I uploaded a wrong file. Now I deleted it and added the correct one. 
Please check it!

**Comment by satoshifuku** [comment]
Thank you :) I'll check it.
I had been afraid with asking to you. lol

**Comment by hani1986ye** [comment]
> Thank you :) I'll check it.
> I had been afraid with asking to you. lol

You are welcome to ask anytime ^_^

**Comment by satoshifuku** [comment]
Sorry for late to replay.

Awsome! your code is really good.
I'll marge your code.
